
Spring:
  datasource:
    url: jdbc:h2:mem:avrest
    driver-class-name: org.h2.Driver
    username: Admin
    password: 1234
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false